site_name: Model-Based System Engineering

repo_url: https://github.com/Krizsi96/mbse-concept
repo_name: Krizsi96/mbse-concept

theme:
  name: material
  palette:
    scheme: slate

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.tabs

nav:
  - Theory:
      - Let's talk about requirements.md
      - What is Model-Based System Engineering.md

plugins:
  - pub-obsidian:
      links:
        wikilinks_enabled: true
      backlinks:
        enabled: false
  - search
  - glightbox

markdown_extensions:
  - pymdownx.blocks.caption
